### ISSUE TITLE
Register as composer package to require dev and symlink 

### ISSUE THREAD

**Issue by t3easy** [alexanderschnitzler/phpstorm.meta.php-typo3#1]
If the package could be installed via composer as a dev dependency + a symlink this would simplify the usage.

**Comment by etobi** [comment]
I really like the idea.
BTW. You can place the .phpstorm.meta.php anywhere within your project, so you dont need a symlink.
So a pretty simple composer.json should be enough to solve this.

**Comment by alexanderschnitzler** [comment]
Just published it on packagist: https://packagist.org/packages/alexanderschnitzler/phpstorm.meta.php-typo3
Do you need tags? I guess dev-main is just fine, isn't it?

**Comment by t3easy** [comment]
I guess tags are only necessary if the the behavior changes in TYPO3.

**Comment by etobi** [comment]
awesome. works fine without tags.

`composer req alexanderschnitzler/phpstorm.meta.php-typo3`
